server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/tagbangers
          # jwk-set-uri: http://localhost:8080/auth/realms/tagbangers/protocol/openid-connect/certs
